### ISSUE TITLE
@swc/plugin-styled-jsx seems broken in latest versions

### ISSUE THREAD

**Issue by etienne-martin** [swc-project/plugins#173] opened 2023-04-12 15:27 UTC
The error:

```
Error while importing "__wbindgen_placeholder__"."__wbindgen_object_drop_ref": unknown import. Expected Function(FunctionType { params: [I32], results: [] })
```

See the workaround in [this comment](https://github.com/swc-project/plugins/issues/116#issuecomment-1441043322). 

I also had to lock `@swc/core` to version `1.3.14` otherwise I'd get the following error:

```
failed to invoke `@swc/plugin-styled-jsx` as js transform plugin at ../../node_modules/@swc/plugin-styled-jsx/swc_plugin_styled_jsx.wasm
```

It seems that as it is today, `@swc/plugin-styled-jsx` is broken when using the latest versions of the `@swc/plugin-styled-jsx` and `@swc/core` packages.

**Comment by kdy1** [comment] 2023-04-13 02:28
Duplicate of https://github.com/swc-project/plugins/issues/172

**Closed by kdy1** 2023-04-13 02:28 UTC
